"""Репозитории доступа к сущностям БД."""
from .collection_job import (
    add_job_log,
    cancel_job,
    count_active_jobs_for_platform,
    count_active_jobs_for_source,
    count_active_jobs_for_worker,
    count_job_logs,
    count_jobs,
    create_job,
    find_due_sources,
    find_stuck_jobs,
    finish_job_failure,
    finish_job_success,
    finish_job_timeout,
    get_job_by_id,
    get_queue_stats,
    list_job_logs,
    list_jobs,
    pick_next_job,
    recover_stuck_jobs,
    update_job,
)
from .common import utcnow
from .post import (
    get_post_by_id,
    get_post_by_source_and_external,
    get_post_by_vk_id,
    get_recent_posts,
    list_posts_by_owner_id,
    list_posts_by_source_id,
    save_post,
)
from .post_comment import replace_comments_from_vk_collect
from .source import (
    add_audit_log,
    add_source,
    count_audit_logs,
    count_sources,
    delete_source,
    get_source_by_id,
    list_audit_logs,
    list_sources,
    set_source_status,
    soft_delete_source,
    update_source,
)
from .schedule import (
    add_schedule_log,
    count_rules,
    count_schedule_logs,
    count_schedule_logs_since,
    create_rule,
    delete_rule,
    find_rule_for_source,
    get_rule_by_id,
    list_rules,
    list_schedule_logs,
    update_rule,
)
from .source_schwartz import (
    get_source_schwartz_by_source_id,
    replace_source_schwartz,
)
from .post_embedding import (
    get_embedding,
    get_embeddings_by_post_ids,
    list_posts_missing_embedding,
    upsert_embedding,
)
from .story_cluster import (
    archive_stale_clusters,
    count_clusters,
    count_posts_in_cluster,
    count_sources_in_cluster,
    create_cluster,
    delete_all_clustering_data,
    find_nearest_active_cluster,
    get_assignment_by_post,
    get_cluster_by_id,
    list_cluster_post_texts,
    list_clusters,
    list_first_sources,
    list_post_texts_by_cluster,
    list_posts_in_cluster,
    list_posts_in_clusters,
    list_posts_without_assignment,
    list_trending_combined,
    update_cluster_centroid,
    update_cluster_labels,
    upsert_assignment,
)

__all__ = [
    # collection jobs
    "add_job_log",
    "cancel_job",
    "count_active_jobs_for_platform",
    "count_active_jobs_for_source",
    "count_active_jobs_for_worker",
    "count_job_logs",
    "count_jobs",
    "create_job",
    "find_due_sources",
    "find_stuck_jobs",
    "finish_job_failure",
    "finish_job_success",
    "finish_job_timeout",
    "get_job_by_id",
    "get_queue_stats",
    "list_job_logs",
    "list_jobs",
    "pick_next_job",
    "recover_stuck_jobs",
    "update_job",
    # common
    "utcnow",
    # posts
    "get_post_by_id",
    "get_post_by_source_and_external",
    "get_post_by_vk_id",
    "get_recent_posts",
    "list_posts_by_owner_id",
    "list_posts_by_source_id",
    "save_post",
    # comments
    "replace_comments_from_vk_collect",
    # sources
    "add_audit_log",
    "add_source",
    "count_audit_logs",
    "count_sources",
    "delete_source",
    "get_source_by_id",
    "list_audit_logs",
    "list_sources",
    "set_source_status",
    "soft_delete_source",
    "update_source",
    # schwartz
    "get_source_schwartz_by_source_id",
    "replace_source_schwartz",
    # post embeddings
    "get_embedding",
    "get_embeddings_by_post_ids",
    "list_posts_missing_embedding",
    "upsert_embedding",
    # story clusters
    "archive_stale_clusters",
    "count_clusters",
    "count_posts_in_cluster",
    "count_sources_in_cluster",
    "create_cluster",
    "delete_all_clustering_data",
    "find_nearest_active_cluster",
    "get_assignment_by_post",
    "get_cluster_by_id",
    "list_cluster_post_texts",
    "list_clusters",
    "list_first_sources",
    "list_post_texts_by_cluster",
    "list_posts_in_cluster",
    "list_posts_in_clusters",
    "list_posts_without_assignment",
    "list_trending_combined",
    "update_cluster_centroid",
    "update_cluster_labels",
    "upsert_assignment",
    # schedule
    "add_schedule_log",
    "count_rules",
    "count_schedule_logs",
    "count_schedule_logs_since",
    "create_rule",
    "delete_rule",
    "find_rule_for_source",
    "get_rule_by_id",
    "list_rules",
    "list_schedule_logs",
    "update_rule",
]
