"""initial migration

Revision ID: f920d3652acd
Revises: 
Create Date: 2026-04-24 16:30:37.896879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f920d3652acd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vk_post_id', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_owner_id'), 'posts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_posts_vk_post_id'), 'posts', ['vk_post_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('vk_owner_id', sa.BigInteger(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_source'), 'sources', ['source'], unique=False)
    op.create_index(op.f('ix_sources_status'), 'sources', ['status'], unique=False)
    op.create_index(op.f('ix_sources_vk_owner_id'), 'sources', ['vk_owner_id'], unique=False)
    op.create_table('post_schwartz_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('self_direction', sa.Float(), nullable=False),
    sa.Column('stimulation', sa.Float(), nullable=False),
    sa.Column('hedonism', sa.Float(), nullable=False),
    sa.Column('achievement', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('security', sa.Float(), nullable=False),
    sa.Column('conformity', sa.Float(), nullable=False),
    sa.Column('tradition', sa.Float(), nullable=False),
    sa.Column('benevolence', sa.Float(), nullable=False),
    sa.Column('universalism', sa.Float(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_schwartz_analysis_post_id'), 'post_schwartz_analysis', ['post_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_schwartz_analysis_post_id'), table_name='post_schwartz_analysis')
    op.drop_table('post_schwartz_analysis')
    op.drop_index(op.f('ix_sources_vk_owner_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_status'), table_name='sources')
    op.drop_index(op.f('ix_sources_source'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_posts_vk_post_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_owner_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
